[fw.app]
id = "tracing-otlp"
name = "tracing示例"
desc = "tracing示例"
version = "1.0.0"

[fw.web_server]
port = 8089
doc_urls = [["test env", "http://localhost:8089/"]]

[fw.db]
url = "postgres://postgres:ENC(5892ae51dbeedacdf10ba4c0d7af42a7)@localhost:5432/test"

[fw.log]
level = "info"
endpoint = "http://localhost:4317"
protocol = "grpc"
server_name = "tracing示例"
